services:
  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - course_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://course_db:5432/${POSTGRES_DB}

  course_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - course_db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

volumes:
  course_db: