services:
  course_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=307t0HrY
      - POSTGRES_DB=CourseDB
    volumes:
      - course_db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

  app:
    build: .
    ports:
      - "0.0.0.0:8081:8081"
    depends_on:
      - course_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://course_db:5432/CourseDB
      - JAVA_OPTS=-Xmx512m

volumes:
  course_db: