server:
  address: 127.0.0.1
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/CourseDB
    username: postgres
    password: 307t0HrY
  flyway:
    baseline-on-migrate: true

  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: none