# server:
# address: 127.0.0.1
# port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://course-db:5432/CourseDB
    username: postgres
    password: 307t0HrY
  flyway:
    baseline-on-migrate: true
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: none