CREATE TABLE Course
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    author      VARCHAR(100),
    duration    INT,                          -- длительность курса в часах или днях
    status      VARCHAR(20) DEFAULT 'active', -- статус: активный, архивный, ожидающий и т.д.
    price       DECIMAL(10, 2),               -- цена курса
    start_date  DATE,
    end_date    DATE,
    created_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Lesson
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    course_id   INT          NOT NULL,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    order_index INT,  -- порядок следования урока в рамках курса
    materials   TEXT, -- ссылки на материалы урока
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (course_id) REFERENCES Course (id)
);

CREATE TABLE Enrollment
(
    id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    course_id       INT NOT NULL,
    user_id         INT NOT NULL,
    status          VARCHAR(20) DEFAULT 'active', -- статус записи: активный, завершенный и т.д.
    enrollment_date DATE,
    completed       BOOLEAN     DEFAULT FALSE,    -- флаг завершения курса
    created_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (course_id) REFERENCES Course (id)
);

CREATE TABLE CourseMaterial
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    course_id   INT         NOT NULL,
    type        VARCHAR(50) NOT NULL, -- тип материала (видео, текст, задание и т.д.)
    title       VARCHAR(255),
    description TEXT,
    file_url    VARCHAR(255),         -- ссылка на файл
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (course_id) REFERENCES Course (id)
);